#+TITLE: On this page
#+DATE: <2025-04-30 qua>
#+AUTHOR: André Meneses
#+FILETAGS: :meta:emacs:
#+DESCRIPTION: Some technicalities of the inner workings of this website. 

* On philosophy

This site started because I was already using Emacs and Org mode for some of my writing, and publishing from the same environment seemed convenient.

I also wanted a public place for notes and thoughts that I felt like putting online, without requiring them to become something more polished.

The site is influenced by [[https://gwern.net][Gwern]] and [[https://andymatuschak.org][Andy Matuschak]], both in presentation and in the way they use personal websites for writing.

* On mechanics

The site is written in Emacs using Org mode and published to HTML with =org-publish= and =ox-tufte=. It is deployed to GitHub Pages through GitHub Actions.

The visual style is based on Tufte CSS, mostly because I like its typography and support for sidenotes and margin notes. Since Tufte CSS was designed for HTML, =ox-tufte= handles the corresponding Org markup during export.

The site also integrates with org-roam. I added a few functions to preserve links between notes during publishing and to generate the archive and latest-posts sections automatically. The navigation bar and parts of the stylesheet are custom.

I initially experimented with Hugo and =ox-hugo=, but eventually preferred using =org-publish= directly. There are fewer layers between the Org files and the resulting site, which makes the setup easier for me to understand and modify.

The original =build-site.el= was adapted from [[https://systemcrafters.net][System Crafters]] and has since been modified substantially for this site. The current version is available [[https://github.com/andre-meneses/andre-meneses.github.io/blob/main/build-site.el][on GitHub]].
